version: "3.8"

services: 
    #container
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: sqlserver-2022
        environment:
            ACCEPT_EULA: "y"
            MSSQL_SA_PASSWORD: "chien"
        ports:
        -  "1433:1433"
        restart: "always"
        